//! Cloudflare Pages deployment adapter.
//!
//! Output structure:
//! ```text
//! dist/
//! ├── index.html
//! ├── assets/
//! ├── _worker.js            # Workers script (if ActionNodes exist)
//! └── wrangler.toml         # Wrangler config
//! ```

use std::collections::HashMap;
use std::path::PathBuf;

use anyhow::Result;
use voce_adapter_core::{Adapter, Bundle, CompiledOutput, DeployConfig, DeployResult};

/// Cloudflare Pages adapter.
pub struct CloudflareAdapter {
    output_dir: PathBuf,
}

impl CloudflareAdapter {
    /// Create a new Cloudflare adapter.
    pub fn new(output_dir: PathBuf) -> Self {
        Self { output_dir }
    }
}

impl Default for CloudflareAdapter {
    fn default() -> Self {
        Self::new(PathBuf::from("dist"))
    }
}

impl Adapter for CloudflareAdapter {
    fn name(&self) -> &str {
        "cloudflare"
    }

    fn prepare(&self, compiled: &CompiledOutput, config: &DeployConfig) -> Result<Bundle> {
        let mut files: HashMap<PathBuf, Vec<u8>> = HashMap::new();

        // Static files
        files.insert(
            PathBuf::from("index.html"),
            compiled.html.as_bytes().to_vec(),
        );
        for (name, data) in &compiled.assets {
            files.insert(PathBuf::from(format!("assets/{name}")), data.clone());
        }

        // _worker.js if there are ActionNodes
        if !compiled.actions.is_empty() {
            let worker = generate_worker(&compiled.actions);
            files.insert(PathBuf::from("_worker.js"), worker.into_bytes());
        }

        // wrangler.toml
        let project_name = config
            .settings
            .get("project_name")
            .cloned()
            .unwrap_or_else(|| compiled.meta.name.clone());
        let wrangler = format!(
            r#"name = "{project_name}"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."
"#
        );
        files.insert(PathBuf::from("wrangler.toml"), wrangler.into_bytes());

        let summary = format!(
            "Cloudflare Pages: {} static files{}",
            compiled.assets.len() + 1,
            if compiled.actions.is_empty() {
                String::new()
            } else {
                format!(", _worker.js with {} routes", compiled.actions.len())
            }
        );

        Ok(Bundle {
            output_dir: self.output_dir.clone(),
            files,
            summary,
        })
    }

    fn deploy(&self, bundle: &Bundle, config: &DeployConfig) -> Result<DeployResult> {
        bundle.write_to_disk()?;

        let project_name = config
            .settings
            .get("project_name")
            .cloned()
            .unwrap_or_else(|| "voce-site".to_string());

        let wrangler_available = std::process::Command::new("wrangler")
            .arg("--version")
            .output()
            .is_ok();

        if wrangler_available {
            let output = std::process::Command::new("wrangler")
                .args(["pages", "deploy", &bundle.output_dir.to_string_lossy()])
                .args(["--project-name", &project_name])
                .output()?;

            let stdout = String::from_utf8_lossy(&output.stdout);
            Ok(DeployResult {
                url: stdout
                    .lines()
                    .find(|l| l.contains("https://"))
                    .map(|s| s.trim().to_string()),
                deployment_id: None,
                message: format!("Deployed to Cloudflare Pages: {stdout}"),
            })
        } else {
            Ok(DeployResult {
                url: None,
                deployment_id: None,
                message: format!(
                    "Cloudflare bundle written to {}/ — run `wrangler pages deploy {}` to deploy",
                    bundle.output_dir.display(),
                    bundle.output_dir.display()
                ),
            })
        }
    }
}

/// Generate a Cloudflare Workers script that routes ActionNode handlers.
fn generate_worker(actions: &[voce_adapter_core::ActionHandler]) -> String {
    let mut routes = String::new();
    for action in actions {
        routes.push_str(&format!(
            r#"  if (url.pathname === '{route}' && request.method === '{method}') {{
    // ActionNode: {node_id}
    {handler_code}
    return new Response(JSON.stringify({{ ok: true }}), {{
      headers: {{ 'Content-Type': 'application/json' }}
    }});
  }}
"#,
            route = action.route,
            method = action.method,
            node_id = action.node_id,
            handler_code = action.handler_code,
        ));
    }

    format!(
        r#"// Auto-generated by Voce IR compiler
export default {{
  async fetch(request, env) {{
    const url = new URL(request.url);
{routes}
    // Fall through to static assets
    return env.ASSETS.fetch(request);
  }}
}};
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use voce_adapter_core::{ActionHandler, ProjectMeta};

    fn sample_with_action() -> CompiledOutput {
        CompiledOutput {
            html: "<html><body>Hello</body></html>".to_string(),
            assets: HashMap::new(),
            actions: vec![ActionHandler {
                route: "/api/submit".to_string(),
                method: "POST".to_string(),
                node_id: "form-submit".to_string(),
                handler_code: "// handle submit".to_string(),
            }],
            meta: ProjectMeta {
                name: "my-site".to_string(),
                ..Default::default()
            },
        }
    }

    #[test]
    fn prepare_creates_worker_and_wrangler() {
        let adapter = CloudflareAdapter::default();
        let bundle = adapter
            .prepare(&sample_with_action(), &DeployConfig::default())
            .unwrap();

        assert!(bundle.files.contains_key(&PathBuf::from("_worker.js")));
        assert!(bundle.files.contains_key(&PathBuf::from("wrangler.toml")));
    }

    #[test]
    fn worker_routes_action() {
        let adapter = CloudflareAdapter::default();
        let bundle = adapter
            .prepare(&sample_with_action(), &DeployConfig::default())
            .unwrap();

        let worker = String::from_utf8_lossy(
            bundle.files.get(&PathBuf::from("_worker.js")).unwrap(),
        );
        assert!(worker.contains("/api/submit"));
        assert!(worker.contains("request.method === 'POST'"));
    }

    #[test]
    fn no_worker_without_actions() {
        let compiled = CompiledOutput {
            html: "<html></html>".to_string(),
            assets: HashMap::new(),
            actions: vec![],
            meta: ProjectMeta::default(),
        };
        let adapter = CloudflareAdapter::default();
        let bundle = adapter
            .prepare(&compiled, &DeployConfig::default())
            .unwrap();

        assert!(!bundle.files.contains_key(&PathBuf::from("_worker.js")));
    }

    #[test]
    fn wrangler_toml_has_project_name() {
        let adapter = CloudflareAdapter::default();
        let bundle = adapter
            .prepare(&sample_with_action(), &DeployConfig::default())
            .unwrap();

        let toml = String::from_utf8_lossy(
            bundle.files.get(&PathBuf::from("wrangler.toml")).unwrap(),
        );
        assert!(toml.contains("name = \"my-site\""));
    }
}
