//! Netlify deployment adapter.
//!
//! Output structure:
//! ```text
//! publish/
//! ├── index.html
//! ├── assets/
//! ├── netlify.toml
//! └── netlify/
//!     └── functions/
//!         └── <route>.js     # Netlify Functions from ActionNodes
//! ```

use std::collections::HashMap;
use std::path::PathBuf;

use anyhow::Result;
use voce_adapter_core::{Adapter, Bundle, CompiledOutput, DeployConfig, DeployResult};

/// Netlify deployment adapter.
pub struct NetlifyAdapter {
    output_dir: PathBuf,
}

impl NetlifyAdapter {
    /// Create a new Netlify adapter.
    pub fn new(output_dir: PathBuf) -> Self {
        Self { output_dir }
    }
}

impl Default for NetlifyAdapter {
    fn default() -> Self {
        Self::new(PathBuf::from("publish"))
    }
}

impl Adapter for NetlifyAdapter {
    fn name(&self) -> &str {
        "netlify"
    }

    fn prepare(&self, compiled: &CompiledOutput, _config: &DeployConfig) -> Result<Bundle> {
        let mut files: HashMap<PathBuf, Vec<u8>> = HashMap::new();

        // Static files
        files.insert(
            PathBuf::from("index.html"),
            compiled.html.as_bytes().to_vec(),
        );
        for (name, data) in &compiled.assets {
            files.insert(PathBuf::from(format!("assets/{name}")), data.clone());
        }

        // Netlify Functions from ActionNodes
        for action in &compiled.actions {
            let func_name = action
                .route
                .trim_start_matches('/')
                .replace('/', "-");
            let func = generate_netlify_function(action);
            files.insert(
                PathBuf::from(format!("netlify/functions/{func_name}.js")),
                func.into_bytes(),
            );
        }

        // netlify.toml
        let mut redirects = String::new();
        for action in &compiled.actions {
            let func_name = action
                .route
                .trim_start_matches('/')
                .replace('/', "-");
            redirects.push_str(&format!(
                "\n[[redirects]]\n  from = \"{}\"\n  to = \"/.netlify/functions/{}\"\n  status = 200\n",
                action.route, func_name
            ));
        }

        let netlify_toml = format!(
            r#"[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
{redirects}"#
        );
        files.insert(PathBuf::from("netlify.toml"), netlify_toml.into_bytes());

        let func_count = compiled.actions.len();
        let summary = format!(
            "Netlify: {} static files, {func_count} functions",
            compiled.assets.len() + 1
        );

        Ok(Bundle {
            output_dir: self.output_dir.clone(),
            files,
            summary,
        })
    }

    fn deploy(&self, bundle: &Bundle, _config: &DeployConfig) -> Result<DeployResult> {
        bundle.write_to_disk()?;

        let netlify_available = std::process::Command::new("netlify")
            .arg("--version")
            .output()
            .is_ok();

        if netlify_available {
            let output = std::process::Command::new("netlify")
                .args(["deploy", "--dir", &bundle.output_dir.to_string_lossy()])
                .output()?;

            let stdout = String::from_utf8_lossy(&output.stdout);
            Ok(DeployResult {
                url: stdout
                    .lines()
                    .find(|l| l.contains("https://"))
                    .map(|s| s.trim().to_string()),
                deployment_id: None,
                message: format!("Deployed to Netlify: {stdout}"),
            })
        } else {
            Ok(DeployResult {
                url: None,
                deployment_id: None,
                message: format!(
                    "Netlify bundle written to {}/ — run `netlify deploy --dir {}` to deploy",
                    bundle.output_dir.display(),
                    bundle.output_dir.display()
                ),
            })
        }
    }
}

/// Generate a Netlify Function from an ActionHandler.
fn generate_netlify_function(action: &voce_adapter_core::ActionHandler) -> String {
    format!(
        r#"// Auto-generated by Voce IR compiler
// ActionNode: {node_id} ({method} {route})

export default async function handler(req, context) {{
  if (req.method !== '{method}') {{
    return new Response(JSON.stringify({{ error: 'Method not allowed' }}), {{
      status: 405,
      headers: {{ 'Content-Type': 'application/json' }}
    }});
  }}

  // TODO: Implement handler logic
  {handler_code}

  return new Response(JSON.stringify({{ ok: true }}), {{
    status: 200,
    headers: {{ 'Content-Type': 'application/json' }}
  }});
}}

export const config = {{
  path: "{route}"
}};
"#,
        node_id = action.node_id,
        method = action.method,
        route = action.route,
        handler_code = action.handler_code,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use voce_adapter_core::{ActionHandler, ProjectMeta};

    fn sample_with_action() -> CompiledOutput {
        CompiledOutput {
            html: "<html><body>Hello</body></html>".to_string(),
            assets: HashMap::new(),
            actions: vec![ActionHandler {
                route: "/api/contact".to_string(),
                method: "POST".to_string(),
                node_id: "contact-submit".to_string(),
                handler_code: "// handle contact".to_string(),
            }],
            meta: ProjectMeta {
                name: "test".to_string(),
                ..Default::default()
            },
        }
    }

    #[test]
    fn prepare_creates_function_and_config() {
        let adapter = NetlifyAdapter::default();
        let bundle = adapter
            .prepare(&sample_with_action(), &DeployConfig::default())
            .unwrap();

        assert!(bundle
            .files
            .contains_key(&PathBuf::from("netlify/functions/api-contact.js")));
        assert!(bundle.files.contains_key(&PathBuf::from("netlify.toml")));
    }

    #[test]
    fn netlify_toml_has_redirect() {
        let adapter = NetlifyAdapter::default();
        let bundle = adapter
            .prepare(&sample_with_action(), &DeployConfig::default())
            .unwrap();

        let toml = String::from_utf8_lossy(
            bundle.files.get(&PathBuf::from("netlify.toml")).unwrap(),
        );
        assert!(toml.contains("from = \"/api/contact\""));
        assert!(toml.contains("to = \"/.netlify/functions/api-contact\""));
    }

    #[test]
    fn function_exports_handler() {
        let adapter = NetlifyAdapter::default();
        let bundle = adapter
            .prepare(&sample_with_action(), &DeployConfig::default())
            .unwrap();

        let func = String::from_utf8_lossy(
            bundle
                .files
                .get(&PathBuf::from("netlify/functions/api-contact.js"))
                .unwrap(),
        );
        assert!(func.contains("export default async function handler"));
        assert!(func.contains("req.method !== 'POST'"));
    }
}
